### ISSUE TITLE
Omit peptides containing Cys

### ISSUE THREAD

**Issue by patrick-willems** [MeenaChoi/MSstats#118]
Dear MSstats team,

I was wondering whether there would be an easy argument to provide in the _MaxQtoMSstatsFormat_ function to indicate to skip cysteine-containing peptides (I do not want to use these for label-free quantification)? I saw there was for instance also the argument 'RemoveOxidationMpeptides', hence perhaps some additional argument could be used? Or would it be as simple as trimming down the evidence table?

Thanks in advance
Patrick

**Comment by mstaniak** [comment]
> Or would it be as simple as trimming down the evidence table?

correct, it's easiest to just remove such peptides before applying our converter

**Comment by patrick-willems** [comment]
Ok thanks! Just to be sure.
