### ISSUE TITLE
OpenMStoMSstatsFormat error 

### ISSUE THREAD

**Issue by daichengxin** [MeenaChoi/MSstats#140]
Hi all, The  error is reported when performing `OpenMStoMSstatsFormat ` functions.  
log info :
```
Error in setnames(x, value) : 
    Can't assign 4 names to a 0 column data.table
  Calls: OpenMStoMSstatsFormat ... colnames<- -> names<- -> names<-.data.table -> setnames
  
```
 
 input file:
 
[sdrf-cellLine3_kai_modified_2024_10_29.sdrf_openms_design_msstats_in.csv](https://github.com/user-attachments/files/17567466/sdrf-cellLine3_kai_modified_2024_10_29.sdrf_openms_design_msstats_in.csv)

version: MSstats 4.10.1   MSstatsConvert 1.15.6

**Comment by ypriverol** [comment]
@tonywu1999 Can you help us here, this is from quantms.

**Comment by tonywu1999** [comment]
Hi,

For experimental designs where there are only 2 bioreplicates (1 per condition), I would advise adding the `removeFewMeasurements = FALSE` flag.  By default, this flag is set to true, where if a peptide is only identified in at most 2 bioreplicates, that peptide will be filtered from the dataset.  

```
OpenMStoMSstatsFormat(input, removeFewMeasurements = FALSE)
```

**Comment by kai-lawsonmcdowall** [comment]
Hi all, I believe I was the one who originally bought up this issue on the QuantMS NF-core Slack. This was indeed the fix. I also ran into the issue where I was using an outdated docker container: `biocontainers/bioconductor-msstats:4.8.3--r43hf17093f_0`, which will fail regardless of the `removeFewMeasurements = FALSE` flag. Switching to `biocontainers/bioconductor-msstats:4.10.0--r43hf17093f_0` seemed to do the trick. 

Thank you every one for your help, QuantMS and MSstats are both awesome tools! :)
