### ISSUE TITLE
MSstats does not work in Skyline

### ISSUE THREAD

**Issue by NBattchi** [MeenaChoi/MSstats#26]
Hello

I try to use MSstats in Skyline but it does not work.
I try to re-install it from (In Skyline) --> Tools --> Tool Store --> MS stats --> Reinstall, but it seems that nothing happens, and the program still does not work.
Please help. I am a simple user of Skyline and do not have experience in programming. But I need MSstats for data analysis. I could send my Skyline file if necessary.
If this is a wrone place to ask this question, please direct me to the right site

Sincerely
Natalia

**Comment by MeenaChoi** [comment]
If you have the issue in Skyline, Skyline support board is the better place that you can get feedback. 
I think that you already posted in Skyline support board and Nick helped. I suggested to uninstall R and MSstats in Skyline and to re-install MSstats in Skyline.

-Meena
