### ISSUE TITLE
MSstat question

### ISSUE THREAD

**Issue by yasijami** [MeenaChoi/MSstats#27]
Hi There,

I had a question regarding using msstats from an output generated from
MaxQuant output on TMT results. The issue is when I use proteingroup
command on the output that I got from protein summarization command on
msstat.

There are 2 type files hat are very similar, one file gives me the
correct proteingroup output whereas the other one looks like all SE,DF
pvalue,adj.pvalue columns are missing their values. I have tried it
many times over and over and the step before which is protein
summarization looks normal in both, but one file does not give the
correct protein Group.

I have sent you the file that works ( GroupComparision-I) and the
other file that did not work(GroupComparision-M)

I appreciate any help. I can also send you all of my R commands.

Thanks,
Yasaman

**Comment by MeenaChoi** [comment]
I'm wondering whether you use MSstatsTMT package, instead of MSstats. MSstats supports DDA, DIA, SRM. MSstatsTMT supports TMT. If you use MSstats, please try MSstatsTMT instead. Here is the link : https://github.com/Vitek-Lab/MSstatsTMT

- Meena

**Comment by yasijami** [comment]
No I am using the correct one, as I said it works for one file but it fails
for the other one. Do you want me to send you my files?
Regards,
Yasi

**Comment by yasijami** [comment]
Here is all my commands 
install.packages("devtools")
devtools::install_github("Vitek-Lab/MSstatsTMT")
library('MSstatsTMT')
?MSstatsTMT
#usage_df <- read.table("evidence-M.txt", sep="\t")
#PIF_cutoff <- 0.7
#usage_df<-usage_df[which(usage_df$PIF>=PIF_cutoff),]

annot.maxquant<-read.csv("M-annotation-MQ.csv",sep=",")
proteinGroups <- read.table("proteinGroups.txt", sep = "\t", header = TRUE)
evi <- read.table("evidence.txt", sep="\t", header=TRUE)
#colnames(evi)
#unique(evi$Raw.file)
# 1. format command (maxqtomsstatstmtformat or pd format command)

processed_input<-MaxQtoMSstatsTMTFormat(evi,proteinGroups, annot.maxquant, fraction = TRUE, rmProt_Only.identified.by.site = FALSE, which.proteinid = "Proteins", useUniquePeptide = TRUE,rmPSM_withMissing_withinRun = TRUE, rmProtein_with1Feature = TRUE, summaryforMultipleRows = sum)
#processed_input<-MaxQtoMSstatsTMTFormat(annot.maxquant,proteinGroups, evi, fraction = TRUE, rmProt_Only.identified.by.site = FALSE, which.proteinid = "Proteins", useUniquePeptide = TRUE,rmPSM_withMissing_withinRun = TRUE, rmProtein_with1Feature = FALSE, summaryforMultipleRows = sum)
#2. protein summarization command (calculate protein quantities)
?proteinSummarization
protein_quant<-proteinSummarization(processed_input, normalization = FALSE,
                                    MBimpute = TRUE, maxQuantileforCensored = NULL)
write.csv(protein_quant,"Pr-Sum-MQ-TMT-M-Mix.csv") 

# 3. group comparison command (statistical testing and multiple hypothesis testing correction)

output<-groupComparisonTMT(protein_quant, contrast.matrix = "pairwise",
                           remove_norm_channel = TRUE,
                           adj.method = "BH")

write.csv(output,"GroupComparision-MQ-TMT-M.csv")


Regards,
Yasi

**Comment by MeenaChoi** [comment]
If you used MSstatsTMT package, please post the question in MSstatsTMT github or google group (https://groups.google.com/forum/#!forum/msstats).
